# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30b9778071aeb76a8135fffdb4f6619b8e0c9a768b6b04a41c9eadc36b32fd1ed94c7369b562485f81140066888d11f160acf931276638673ef472d6ed600c6

test:
  secret_key_base: 5a1ccb2d2db15575cb0f8850c7510ee2d238c4f0e7f0fad55e1094820ba91fae5034207a8345aa40873d03945965d739d6223ff40040322159a0e4b3f308c687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
