# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e4903d2336588cc36bc12e716e0cc2636acb2f356f3bb7c202ac797e83291e5a4f8052dafcc8302482cc3fb3a88b7fef58857d67c3a113a957a2a57bd73307

test:
  secret_key_base: 0bd86a078af5fa9b654f41fe880819571e64f87d8f6641e22fc475eb8215cd7dc5a2e60bd9e743ce5b97ac74f2822168452fe8b64b23f40b7fc24916b072c1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
